COMMENT=	 Flash program for STM32 using the ST serial bootloader

GH_ACCOUNT=	stlink-org
GH_PROJECT=	stlink
GH_TAGNAME=	v1.8.0

CATEGORIES=	sysutils

HOMEPAGE=	https://sourceforege.net/p/stm32flash

# GPLv2
PERMIT_PACKAGE=	Yes

MODULES=	devel/cmake

WANTLIB+=	c

.include <bsd.port.mk>
